"use client";

import { useState } from "react";
import { explainMatch } from "@/lib/api";

/**
 * One drug row's explanation. Shows the saved Gemini text when there is one. Otherwise shows an
 * "Explain more" button: clicking it makes one Gemini request for this patient and this drug,
 * and the server saves the answer so the next visit shows it without a request.
 */
export function ExplainMore({ patientId, drugId, saved }: { patientId: string; drugId: string; saved: string | null }) {
  const [text, setText] = useState<string | null>(saved);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // The page re-fetches on a timer. If the server now has saved text (for example generated in another tab), show it.
  const [seenSaved, setSeenSaved] = useState(saved);
  if (saved !== seenSaved) {
    setSeenSaved(saved);
    if (saved) setText(saved);
  }

  async function generate() {
    setLoading(true);
    setError(null);
    try {
      setText(await explainMatch(patientId, drugId));
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong.");
    } finally {
      setLoading(false);
    }
  }

  if (text) {
    return (
      <p className="pt-1 text-[13.5px] leading-[1.55]">
        <span className="font-medium">Why surfaced · </span>
        {text}
        <span className="ml-2 whitespace-nowrap rounded border border-line-2 px-1.5 py-px align-middle font-mono text-[10px] uppercase tracking-[0.04em] text-ink-2">
          Generated by Gemini
        </span>
      </p>
    );
  }

  return (
    <div className="flex flex-wrap items-center gap-3 pt-1">
      <button
        type="button"
        onClick={generate}
        disabled={loading}
        className="h-[30px] rounded-lg border border-line-2 bg-surface px-3 text-[13px] font-medium hover:bg-fill disabled:cursor-wait disabled:opacity-60"
      >
        {loading ? "Asking Gemini..." : "Explain more"}
      </button>
      {error ? <span className="text-[13px] text-red">{error}</span> : null}
    </div>
  );
}
