-- Dosely workflow tables
--
-- What this does: adds the tables the recall job and the screens write to and read from.
-- What it does not do: it changes no existing row, drops nothing, and renames nothing.
-- Safe to run more than once. Every statement uses IF NOT EXISTS.
--
-- How to run: Supabase dashboard > SQL Editor > paste this whole file > Run.
--
-- Conventions, matching the existing tables:
--   ids are bigint identity columns
--   a practice is identified by clinic_name, the same text as ehr_doctors.clinic_name
--   row level security is ON with no policies, so only the secret key and
--   scheduled database jobs can read or write. The publishable key cannot.
--
-- Time rule used by the recall job: it writes each event with the timestamp at which the
-- event "happens", which can be a few minutes in the future. Every screen query therefore
-- filters on ts <= now() (events) or created_at <= now() (appointments).


-- ------------------------------------------------------------------
-- 1. Two flags on patients. Both default to false, so no existing row changes meaning.
-- ------------------------------------------------------------------

alter table public.ehr_patients add column if not exists on_hold        boolean not null default false;
alter table public.ehr_patients add column if not exists do_not_contact boolean not null default false;

-- The recall job filters on these two columns every run.
create index if not exists ehr_patients_due_idx    on public.ehr_patients (next_followup_due);
create index if not exists ehr_patients_doctor_idx on public.ehr_patients (doctor_id);


-- ------------------------------------------------------------------
-- 2. Calendar: open times and booked visits
-- ------------------------------------------------------------------

create table if not exists public.ehr_slots (
    id                   bigint generated by default as identity primary key,
    doctor_id            bigint not null references public.ehr_doctors(id),
    starts_at            timestamptz not null,
    ends_at              timestamptz not null,
    booked_by_patient_id bigint references public.ehr_patients(id),
    -- One slot per provider per start time. Booking sets booked_by_patient_id with
    -- "where booked_by_patient_id is null", so two bookers can never take the same slot.
    unique (doctor_id, starts_at)
);

create index if not exists ehr_slots_open_idx
    on public.ehr_slots (doctor_id, starts_at)
    where booked_by_patient_id is null;


-- ------------------------------------------------------------------
-- 3. Recall runs and outreach
-- ------------------------------------------------------------------

-- One row per execution of the recall job.
create table if not exists public.recall_runs (
    id               bigint generated by default as identity primary key,
    as_of            timestamptz not null,               -- the moment the run treats as "now"
    trigger          text not null default 'cron'
                     check (trigger in ('cron', 'manual', 'backfill')),
    patients_found   integer not null default 0,
    outreach_created integer not null default 0,
    started_at       timestamptz not null default now(),
    finished_at      timestamptz
);

-- The run log. Each run records what it looked at and what it passed over, so the
-- filters can be checked from the table:
--   overdue_total = patients_found + already flagged earlier + every skipped_* count
-- Written as ALTERs so they apply whether or not the table above already existed.
alter table public.recall_runs add column if not exists overdue_total          integer not null default 0;  -- due date before as_of
alter table public.recall_runs add column if not exists skipped_no_consent     integer not null default 0;  -- neither call nor text consent
alter table public.recall_runs add column if not exists skipped_on_hold        integer not null default 0;
alter table public.recall_runs add column if not exists skipped_do_not_contact integer not null default 0;
alter table public.recall_runs add column if not exists skipped_already_open   integer not null default 0;  -- outreach already in progress
alter table public.recall_runs add column if not exists detail                 jsonb   not null default '{}'::jsonb;  -- per-clinic counts

-- One row per attempt to reach one patient.
-- status values: queued, calling, text_sent, booked, needs_attention,
--                declined, seen, no_show, cancelled, closed
create table if not exists public.outreach (
    id            bigint generated by default as identity primary key,
    patient_id    bigint not null references public.ehr_patients(id),
    doctor_id     bigint not null references public.ehr_doctors(id),
    clinic_name   text   not null,
    recall_run_id bigint references public.recall_runs(id),
    channel       text   not null default 'voice' check (channel in ('voice', 'sms')),
    status        text   not null default 'queued',
    call_sid      text,                                  -- set only for real carrier calls
    simulated     boolean not null default true,         -- false only for whitelisted demo phones
    created_at    timestamptz not null default now(),
    updated_at    timestamptz not null default now()
);

create index if not exists outreach_patient_idx on public.outreach (patient_id, created_at desc);
create index if not exists outreach_clinic_idx  on public.outreach (clinic_name, status);
create unique index if not exists outreach_call_sid_idx on public.outreach (call_sid) where call_sid is not null;

-- A patient can have at most one outreach in progress. A second insert fails instead
-- of calling the same person twice.
create unique index if not exists outreach_one_open_per_patient
    on public.outreach (patient_id)
    where status in ('queued', 'calling', 'text_sent', 'booked');


-- ------------------------------------------------------------------
-- 4. Booked visits
-- ------------------------------------------------------------------

-- status values: scheduled, completed, no_show, cancelled
create table if not exists public.ehr_appointments (
    id               bigint generated by default as identity primary key,
    patient_id       bigint not null references public.ehr_patients(id),
    doctor_id        bigint not null references public.ehr_doctors(id),
    slot_id          bigint references public.ehr_slots(id),   -- null for generated history
    outreach_id      bigint references public.outreach(id),    -- null when the practice booked it
    appointment_date timestamptz not null,
    appointment_type text not null default 'follow_up',
    status           text not null default 'scheduled',
    source           text not null default 'dosely' check (source in ('practice', 'dosely')),
    review_state     text not null default 'new'    check (review_state in ('new', 'kept')),
    created_at       timestamptz not null default now(),       -- when the booking was made
    updated_at       timestamptz not null default now()
);

create index if not exists ehr_appointments_doctor_idx  on public.ehr_appointments (doctor_id, appointment_date);
create index if not exists ehr_appointments_patient_idx on public.ehr_appointments (patient_id, appointment_date desc);


-- ------------------------------------------------------------------
-- 5. What appears on the patient card
-- ------------------------------------------------------------------

create table if not exists public.call_summaries (
    outreach_id       bigint primary key references public.outreach(id),
    contact_result    text not null,                     -- answered, no_answer, busy, failed
    identity_verified boolean not null default false,
    patient_response  text,
    appointment_id    bigint references public.ehr_appointments(id),
    patient_question  text,
    followup_required boolean not null default false,
    duration_seconds  integer,
    call_started_at   timestamptz,
    raw_transcript    jsonb not null default '[]'::jsonb
);

create table if not exists public.sms_messages (
    id          bigint generated by default as identity primary key,
    outreach_id bigint references public.outreach(id),
    patient_id  bigint not null references public.ehr_patients(id),
    direction   text not null check (direction in ('out', 'in')),
    kind        text,                                    -- fallback, slot_options, confirmation, reschedule, reassign, reply
    body        text not null,
    message_sid text,                                    -- carrier id, used to ignore duplicate webhooks
    status      text not null default 'sent',
    simulated   boolean not null default true,
    at          timestamptz not null default now()
);

create index if not exists sms_messages_patient_idx on public.sms_messages (patient_id, at);
create unique index if not exists sms_messages_sid_idx on public.sms_messages (message_sid) where message_sid is not null;

-- Open questions for clinic staff. resolved_at is null while the item is open.
create table if not exists public.action_items (
    id          bigint generated by default as identity primary key,
    patient_id  bigint not null references public.ehr_patients(id),
    outreach_id bigint references public.outreach(id),
    text        text not null,
    created_at  timestamptz not null default now(),
    resolved_at timestamptz
);

create index if not exists action_items_open_idx on public.action_items (patient_id) where resolved_at is null;


-- ------------------------------------------------------------------
-- 6. Matcher output. One row per patient and drug that passed.
--    similarity is internal and must never be sent to the web app.
-- ------------------------------------------------------------------

create table if not exists public.matches (
    id              bigint generated by default as identity primary key,
    patient_id      bigint not null references public.ehr_patients(id),
    drug_id         bigint not null references public.pharma_drugs(id),
    rank            integer not null,
    similarity      double precision,
    why_facts       jsonb not null default '[]'::jsonb,  -- [{ "label": ..., "value": ... }], rendered on the panel
    rules_fired     jsonb not null default '[]'::jsonb,
    reason_text     text,                                -- v1 only, never rendered
    context_hash    text,
    embedding_model text,
    threshold       double precision,
    created_at      timestamptz not null default now(),
    unique (patient_id, drug_id)
);

create index if not exists matches_patient_rank_idx on public.matches (patient_id, rank);


-- ------------------------------------------------------------------
-- 7. Events. Every metric on every dashboard is a count over this one table.
-- ------------------------------------------------------------------
-- type values in use:
--   patient_flagged, match_computed, panel_shown, label_viewed, digest_opened,
--   recall_run_started, outreach_queued, patient_held, patient_released,
--   call_placed, call_answered, call_no_answer, call_busy, call_failed, identity_verified,
--   sms_sent, sms_delivered, sms_reply,
--   appointment_booked, confirmation_sent, booking_kept,
--   appointment_rescheduled, appointment_reassigned, appointment_cancelled,
--   declined, escalated, visit_completed, visit_no_show
--
-- No foreign keys here on purpose. It is an append-only log, and inserts stay fast.

create table if not exists public.events (
    id          bigint generated by default as identity primary key,
    ts          timestamptz not null default now(),
    clinic_name text   not null,
    doctor_id   bigint,
    patient_id  bigint,
    outreach_id bigint,
    drug_id     bigint,
    condition   text,                                    -- the patient's first diagnosis, for the by-condition table
    type        text   not null,
    simulated   boolean not null default true,
    meta        jsonb  not null default '{}'::jsonb
);

-- Which run wrote this event. Null for events that come from a person or a webhook.
-- With this, "everything run 12 did" is: select * from events where recall_run_id = 12.
-- A patient_flagged event also carries meta like {"due": "2026-01-09", "days_overdue": 253}.
alter table public.events add column if not exists recall_run_id bigint;
create index if not exists events_run_idx       on public.events (recall_run_id) where recall_run_id is not null;

create index if not exists events_type_ts_idx   on public.events (type, ts);
create index if not exists events_clinic_ts_idx on public.events (clinic_name, ts);
create index if not exists events_patient_idx   on public.events (patient_id, ts);
create index if not exists events_outreach_idx  on public.events (outreach_id, ts);


-- ------------------------------------------------------------------
-- 8. Row level security: on, with no policies.
--    The secret key and scheduled database jobs bypass it. The publishable key gets nothing.
-- ------------------------------------------------------------------

alter table public.ehr_slots        enable row level security;
alter table public.recall_runs      enable row level security;
alter table public.outreach         enable row level security;
alter table public.ehr_appointments enable row level security;
alter table public.call_summaries   enable row level security;
alter table public.sms_messages     enable row level security;
alter table public.action_items     enable row level security;
alter table public.matches          enable row level security;
alter table public.events           enable row level security;
